spring:
  application:
    name: auth-service
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  config:
    import: "optional:configserver:http://localhost:8088"
    activate:
      on-profile: dev