version: "3.9"

services:
  # ================== POSTGRES ==================
  postgres:
    container_name: dkmicroservices-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ngdangkiet
      - POSTGRES_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ndk-microservices-network

  # ================== CONFIG SERVER ==================
  config-server:
    container_name: dkmicroservices-config-server
    image: 01092002/ndk-config-server:latest
    ports:
      - "8088:8088"
    restart: unless-stopped
    networks:
      - ndk-microservices-network

  # ================== SERVICE REGISTRY ==================
  service-registry:
    container_name: dkmicroservices-service-registry
    image: 01092002/ndk-service-registry:latest
    ports:
      - "8761:8761"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ndk-microservices-network

  # ================== AUTH SERVICE ==================
  auth-service:
    container_name: dkmicroservices-auth-service
    image: 01092002/ndk-auth-service:latest
    ports:
      - "8004:8004"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/employee_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_HIBERNATE_DLL_AUTO=update
      - SPRING_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  # ================== DEPARTMENT SERVICE ==================
  department-service:
    container_name: dkmicroservices-department-service
    image: 01092002/ndk-department-service:latest
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/department_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  # ================== EMPLOYEE SERVICE ==================
  employee-service:
    container_name: dkmicroservices-employee-service
    image: 01092002/ndk-employee-service:latest
    ports:
      - "8002:8002"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/employee_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      message-broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  # ================== NOTIFICATION SERVICE ==================
  notification-service:
    container_name: dkmicroservices-notification-service
    image: 01092002/ndk-notification-service:latest
    ports:
      - "8005:8005"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/notification_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      message-broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
      employee-service:
        condition: service_started
    networks:
      - ndk-microservices-network

  # ================== LOCATION SERVICE ==================
  location-service:
    container_name: dkmicroservices-location-service
    image: 01092002/ndk-location-service:latest
    ports:
      - "8006:8006"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/location_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  # ================== TRACKING SERVICE ==================
  tracking-service:
    container_name: dkmicroservices-tracking-service
    image: 01092002/ndk-tracking-service:latest
    ports:
      - "8007:8007"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=tracking-service
      - SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED=true
      - SPRING_DATA_ELASTICSEARCH.URIS=http://tracking-elasticsearch:9200
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      message-broker:
        condition: service_healthy
      tracking-elasticsearch:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  tracking-elasticsearch:
    container_name: dkmicroservices-tracking-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - ndk-microservices-network

  # ================== RECRUITMENT SERVICE ==================
  recruitment-service:
    container_name: dkmicroservices-recruitment-service
    image: 01092002/ndk-recruitment-service:latest
    ports:
      - "8008:8008"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/recruitment_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      message-broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  # ================== ATTENDANCE SERVICE ==================
  attendance-service:
    container_name: dkmicroservices-attendance-service
    image: 01092002/ndk-attendance-service:latest
    ports:
      - "8009:8009"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/attendance_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ngdangkiet
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      message-broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - ndk-microservices-network

  # ================== API GATEWAY ==================
  api-gateway:
    container_name: dkmicroservices-api-gateway
    image: 01092002/ndk-api-gateway:latest
    ports:
      - "8003:8003"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
      caching-data:
        condition: service_healthy
      message-broker:
        condition: service_healthy
      hazelcast:
        condition: service_started
      management-center:
        condition: service_started
      auth-service:
        condition: service_started
      department-service:
        condition: service_started
      employee-service:
        condition: service_started
      location-service:
        condition: service_started
      tracking-service:
        condition: service_started
      recruitment-service:
        condition: service_started
      attendance-service:
        condition: service_started
    networks:
      - ndk-microservices-network

  # ================== ZIPKIN ==================
  distributed-tracing:
    container_name: dkmicroservices-zipkin
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - ndk-microservices-network

  # ================== RABBIT MQ ==================
  message-broker:
    container_name: dkmicroservices-rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - ndk-microservices-network

  # ================== REDIS ==================
  caching-data:
    container_name: dkmicroservices-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ndk-microservices-network

  # ================== HAZELCAST ==================
  hazelcast:
    container_name: dkmicroservices-hazelcast
    image: hazelcast/hazelcast:5.2.1
    restart: unless-stopped
    ports:
      - "5701:5701"
    networks:
      - ndk-microservices-network
  management-center:
    container_name: dkmicroservices-hazelcast-management
    image: hazelcast/management-center:5.2.1
    ports:
      - "8082:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
    networks:
      - ndk-microservices-network

networks:
  ndk-microservices-network:
    driver: bridge