spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  config:
    import: "optional:configserver:http://localhost:8088"

grpc:
  client:
    grpc-department-service:
      address: static://localhost:8010
      negotiation-type: plaintext
    grpc-employee-service:
      address: static://localhost:8020
      negotiation-type: plaintext