spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8
    basename: classpath:i18n/messages
  config:
    import: "optional:configserver:http://localhost:8088"

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

security:
  auth:
    login-url: /api/v1/auth/login
    header-name: Authorization
    header-prefix: "Bearer "
    secret-key: foobar_123456789_foobar_123456789_foobar_123456789_foobar_123456789

grpc:
  client:
    grpc-department-service:
      address: static://localhost:8010
      negotiation-type: plaintext
    grpc-employee-service:
      address: static://localhost:8020
      negotiation-type: plaintext
    grpc-auth-service:
      address: static://localhost:8040
      negotiation-type: plaintext