version: "3.9"

services:
  # postgres db
  postgres:
    container_name: dkmicroservices-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ngdangkiet
      - POSTGRES_PASSWORD=root
    volumes:
      - ./../init.sql:/docker-entrypoint-initdb.d/init.sql

  # elastic search
  elasticsearch:
    container_name: dkmicroservices-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    volumes:
      - ./es:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # tracking data kibana
  kibana:
    container_name: dkmicroservices-kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # distributed tracing zipkin
  distributed-tracing:
    container_name: dkmicroservices-zipkin
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"

  # message broker
  rabbitmq:
    container_name: dkmicroservices-rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq

  # caching data
  redis:
    container_name: dkmicroservices-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  # hazelcast
  hazelcast:
    container_name: dkmicroservices-hazelcast
    image: hazelcast/hazelcast:5.2.1
    restart: unless-stopped
    ports:
      - "5701:5701"
  management-center:
    container_name: dkmicroservices-hazelcast-management
    image: hazelcast/management-center:5.2.1
    ports:
      - "8082:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast

  # jenkins
  jenkins:
    container_name: dkmicroservices-jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker