server:
  port: 8001

grpc:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    non-secure-port: ${grpc.port}

management:
  tracing:
    sampling:
      probability: 1.0