server:
  port: 8006

#grpc:
#  server:
#    port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    non-secure-port: ${grpc.server.port}

management:
  tracing:
    sampling:
      probability: 1.0